//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEWIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEWIOArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OEWIOArticle()
        {
            this.OEWIOSources = new HashSet<OEWIOSource>();
        }
    
        public System.Guid ID { get; set; }
        public string Article { get; set; }
        public Nullable<System.DateTime> ArticleDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> SourceID { get; set; }
    
        public virtual OEWIOProduct OEWIOProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEWIOSource> OEWIOSources { get; set; }
    }
}
