//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEWIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public class OEWIOProduct
    {
        //public OEWIOProduct()
        //{
        //    //this.OEWIOArticles = new HashSet<OEWIOArticle>();
        //    //this.OEWIOCommentaries = new HashSet<OEWIOCommentary>();
        //    //this.OEWIOProductRegions = new HashSet<OEWIOProductRegion>();
        //    //this.OEWIOSources = new HashSet<OEWIOSource>();
        //}
    
        public System.Guid ID { get; set; }
        public int ProductID { get; set; }
        public string Title { get; set; }
        public System.DateTime ProductDate { get; set; }
        public System.Guid AuthorID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual OEWIOArticle OEWIOArticle { get; set; }
        public virtual OEWIOAuthor OEWIOAuthor { get; set; }
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<OEWIOCommentary> OEWIOCommentaries { get; set; }
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<OEWIOProductRegion> OEWIOProductRegions { get; set; }
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<OEWIOSource> OEWIOSources { get; set; }
    }
}
