//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEWIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEWIORegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OEWIORegion()
        {
            this.OEWIOProductRegions = new HashSet<OEWIOProductRegion>();
        }
    
        public System.Guid ID { get; set; }
        public string RegionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEWIOProductRegion> OEWIOProductRegions { get; set; }
    }
}
