//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEWIO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public  class OEWIOArticle
    {
        //public OEWIOArticle()
        //{
        //    this.OEWIOSources = new HashSet<OEWIOSource>();
        //}
    
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public System.Guid ID { get; set; }
        public int ArticleID { get; set; }
        public string Article { get; set; }
        public System.DateTime ArticleDate { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        //public System.Guid ProductID { get; set; }
        //public System.Guid SourceID { get; set; }
    
        public virtual ICollection<OEWIOProduct> OEWIOProduct { get; set; }
        //public virtual ICollection<OEWIOSource> OEWIOSources { get; set; }
    }
}
