//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEWIO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OEWIOEntities : DbContext
    {
        public OEWIOEntities()
            : base("name=OEWIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OEWIOArticle> OEWIOArticles { get; set; }
        public virtual DbSet<OEWIOAuthor> OEWIOAuthors { get; set; }
        public virtual DbSet<OEWIOCommentary> OEWIOCommentaries { get; set; }
        public virtual DbSet<OEWIOProductRegion> OEWIOProductRegions { get; set; }
        public virtual DbSet<OEWIOProduct> OEWIOProducts { get; set; }
        public virtual DbSet<OEWIORegion> OEWIORegions { get; set; }
        public virtual DbSet<OEWIOSource> OEWIOSources { get; set; }
    }
}
